FROM python:3.11-slim

WORKDIR /app

COPY article_service_requirements.txt .
RUN pip install --no-cache-dir -r article_service_requirements.txt

COPY src/article_service.py .

EXPOSE 8002

CMD ["uvicorn", "article_service:app", "--host", "0.0.0.0", "--port", "8002"]
